### ISSUE TITLE
Listing products (attributes) fails when SQL mode `only_full_group_by` is in effect

### ISSUE THREAD

**Issue by rimas-kudelis** [BitBagCommerce/SyliusElasticsearchPlugin#114]
I can't find a bug about this, so creating a new one. When SQL mode `only_full_group_by` is in effect (which is the default on latest MySQL versions), attempting to load product index results in an error:

![paveikslas](https://user-images.githubusercontent.com/2812673/81180536-d6918380-8fb3-11ea-949f-7161d311bd19.png)

Note that I'm using a somewhat forked version of your plugin, so there is a slight possibility that this is caused by my changes. However, I'm quite certain that it isn't.

**Comment by bondie** [comment]
You can set database options like this:

```yaml
# config/packages/doctrine.yaml
doctrine:
    dbal:
        options:
            1002: 'SET sql_mode=(SELECT REPLACE(@@sql_mode, "ONLY_FULL_GROUP_BY", ""))'
```
