### ISSUE TITLE
Set of filters and products don't appear

### ISSUE THREAD

**Issue by cwa-cc** [BitBagCommerce/SyliusElasticsearchPlugin#217]
Hi, 
I'm using Sylius 1.12 and Symfony 6.2.1
I make a test with a project just install with the default samples.

I just began to work with the plugin, but when I'm going on : `https://127.0.0.1:8001/en_US/products-list/t-shirts/men` I don't see any products.
And I have only Min price and Max price in the left column.

I receive too at the end of the `composer require bitbag/elasticsearch-plugin` this error : `The service "bitbag_sylius_elasticsearch_plugin.controller.action.shop.search" has a dependency on a non-existent service "fos_elastica.finder.bitbag_shop_product".`

Thanks in advance for your help

**Comment by mpysiak** [comment]
Hi @cwa-cc, sorry for the delay,

Copy Elasticsearch index files:

```bash
cp -R ./vendor/bitbag/elasticsearch-plugin/src/Resources/config/indexes ./config
```

And override your `config/packages/fos_elastica.yaml` file settings:

```yaml
imports:
  - { resource: "../indexes/bitbag_shop_products.yml" }
  - { resource: "../indexes/bitbag_option_taxons.yml" }
  - { resource: "../indexes/bitbag_attribute_taxons.yml" }
  - { resource: "../indexes/bitbag_shop_facets.yml" }

parameters:
  bitbag_es_pagination_available_page_limits: [9, 18, 36]
  bitbag_es_pagination_default_limit: 9
  bitbag_es_fuzziness: AUTO
  
twig:
  globals:
    bitbag_es_pagination_available_page_limits: "%bitbag_es_pagination_available_page_limits%"

fos_elastica:
  clients:
    default: { url: '%env(ELASTICSEARCH_URL)%' }
```
