### ISSUE TITLE
Analyzer on localized name (search & index)

### ISSUE THREAD

**Issue by magentix** [BitBagCommerce/SyliusElasticsearchPlugin#25]
Hi,

On index, we can easily use analyzer on localized attribute name with folowing configuration:

```yaml
fos_elastica:
    indexes:
        bitbag_shop_product:
            types:
                default:
                    properties:
                        name_en_us: {analyzer: my_analyzer, property_path: name}
            settings:
                index:
                    analysis:
                        analyzer:
                            my_analyzer:
                                tokenizer: icu_tokenizer
                                filter:
                                    - icu_folding
```

But on search, the only way seems to override **ContainsNameQueryBuilder** with *setFieldAnalyzer* on Match object:

 ```php
    public function buildQuery(array $data): ?AbstractQuery
    {
        $localeCode = $this->localeContext->getLocaleCode();
        $propertyName = $this->productNameNameResolver->resolvePropertyName($localeCode);

        if (!$name = $data[$this->namePropertyPrefix]) {
            return null;
        }

        $nameQuery = new Match();
        $nameQuery->setFieldQuery($propertyName, $name);
        // Added
        $nameQuery->setFieldAnalyzer($propertyName, 'my_analyzer');
        // / Added

        return $nameQuery;
    }
```

Is it the best way? Could it be interesting to propose an alternative?

Regards,
Matthieu
