### ISSUE TITLE
Add new filter of a field from product table

### ISSUE THREAD

**Issue by jcgdjob** [BitBagCommerce/SyliusElasticsearchPlugin#27]
How could I add another filter besides taxon, attribute and option?
Thanks!

**Comment by jcgdjob** [comment]
Done by:
1) decorates: bitbag_sylius_elasticsearch_plugin.controller.request_data_handler.shop_product_list
to add parameter
        $data['name'] = $name;
2) add listener: AppBundle\PropertyBuilder\[name]PropertyBuilder
3) add new querybuilder: AppBundle\QueryBuilder\[name]QueryBuilder
4) decorates: bitbag_sylius_elasticsearch_plugin.query_builder.shop_products
to include [name]QueryBuilder

P.S. you may need to set autowire: false in services.yml

**Comment by jcgdjob** [comment]
Already solved, thanks!

**Comment by F-Locos** [comment]
I'm searching for that too. I'm a bit lost at this step : "add listener: AppBundle\PropertyBuilder[name]PropertyBuilder"

When it will be fire ?

**Comment by jcgdjob** [comment]
Since it's extends from \bitbag\elasticsearch-plugin\src\PropertyBuilder\AbstractBuilder.php
you can look into it for details.

Here's my code for your reference:

```
<?php
namespace AppBundle\PropertyBuilder;
use BitBag\SyliusElasticsearchPlugin\PropertyBuilder\AbstractBuilder;
use Elastica\Document;
use FOS\ElasticaBundle\Event\TransformEvent;
use Sylius\Component\Core\Model\ProductInterface;

final class ProductFieldnamePropertyBuilder extends AbstractBuilder
{
    /**
     * @param TransformEvent $event
     */
    public function consumeEvent(TransformEvent $event): void
    {
        $this->buildProperty($event, ProductInterface::class,
            function (ProductInterface $product, Document $document): void {
                $fieldname = (int) $product->getFieldname();

                $document->set('fieldname', $fieldname);
            }
        );
    }
}
```

```
#services.yml
app.bitbag.syliuselasticsearchplugin.propertybuilder.product_fieldname:
        class: AppBundle\PropertyBuilder\ProductFieldnamePropertyBuilder
        tags:
            - { name: kernel.event_subscriber }
```

**Comment by jcgdjob** [comment]
```
<?php
namespace AppBundle\QueryBuilder;
use BitBag\SyliusElasticsearchPlugin\QueryBuilder\QueryBuilderInterface;
use Elastica\Query\AbstractQuery;
use Elastica\Query\Term;

final class HasFieldnameQueryBuilder implements QueryBuilderInterface
{
    /**
     * {@inheritdoc}
     */
    public function buildQuery(array $data): ?AbstractQuery
    {
        $fieldnameQuery = new Term();
        $fieldnameQuery->setTerm('fieldname', $data['fieldname']);
        return $fieldnameQuery;
    }
}
```

```
<?php

namespace AppBundle\QueryBuilder;

use AppBundle\QueryBuilder\HasFieldnameQueryBuilder;
use BitBag\SyliusElasticsearchPlugin\QueryBuilder\QueryBuilderInterface;
use Elastica\Query\AbstractQuery;
use Elastica\Query\BoolQuery;

final class ShopProductsQueryBuilder implements QueryBuilderInterface
{

...
    /**
     * @var QueryBuilderInterface
     */
    private $HasFieldnameQueryBuilder;

    /**
     * @param QueryBuilderInterface $isEnabledQueryBuilder
     * @param QueryBuilderInterface $hasChannelQueryBuilder
     * @param QueryBuilderInterface $containsNameQueryBuilder
     * @param QueryBuilderInterface $hasTaxonQueryBuilder
     * @param QueryBuilderInterface $hasOptionsQueryBuilder
     * @param QueryBuilderInterface $hasAttributesQueryBuilder
     * @param QueryBuilderInterface $hasPriceBetweenQueryBuilder
     * @param QueryBuilderInterface $HasFieldnameQueryBuilder
     * @param string $optionPropertyPrefix
     * @param string $attributePropertyPrefix
     */
    public function __construct(
        QueryBuilderInterface $isEnabledQueryBuilder,
        QueryBuilderInterface $hasChannelQueryBuilder,
        QueryBuilderInterface $containsNameQueryBuilder,
        QueryBuilderInterface $hasTaxonQueryBuilder,
        QueryBuilderInterface $hasOptionsQueryBuilder,
        QueryBuilderInterface $hasAttributesQueryBuilder,
        QueryBuilderInterface $hasPriceBetweenQueryBuilder,
        QueryBuilderInterface $HasFieldnameQueryBuilder,
        string $optionPropertyPrefix,
        string $attributePropertyPrefix
    ) {
        $this->isEnabledQueryBuilder = $isEnabledQueryBuilder;
        $this->hasChannelQueryBuilder = $hasChannelQueryBuilder;
        $this->containsNameQueryBuilder = $containsNameQueryBuilder;
        $this->hasTaxonQueryBuilder = $hasTaxonQueryBuilder;
        $this->hasOptionsQueryBuilder = $hasOptionsQueryBuilder;
        $this->hasAttributesQueryBuilder = $hasAttributesQueryBuilder;
        $this->hasPriceBetweenQueryBuilder = $hasPriceBetweenQueryBuilder;
        $this->HasFieldnameQueryBuilder = $HasFieldnameQueryBuilder;
        $this->optionPropertyPrefix = $optionPropertyPrefix;
        $this->attributePropertyPrefix = $attributePropertyPrefix;
    }

    /**
     * {@inheritdoc}
     */
    public function buildQuery(array $data): AbstractQuery
    {
        $boolQuery = new BoolQuery();

...

        $fieldnameQuery = $this->HasFieldnameQueryBuilder->buildQuery($data);
        $this->addMustIfNotNull($fieldnameQuery, $boolQuery);

        $this->resolveOptionQuery($boolQuery, $data);
        $this->resolveAttributeQuery($boolQuery, $data);

        return $boolQuery;
    }
}

```

```
#services.yml
    app.bitbag.syliuselasticsearchplugin.query_builder.has_fieldname:
        class: AppBundle\QueryBuilder\HasFieldnameQueryBuilder

    app.bitbag.syliuselasticsearchplugin.query_builder.shop_products:
        decorates: bitbag_sylius_elasticsearch_plugin.query_builder.shop_products
        class: AppBundle\QueryBuilder\ShopProductsQueryBuilder
        arguments:
           - "@bitbag_sylius_elasticsearch_plugin.query_builder.is_enabled"
           - "@bitbag_sylius_elasticsearch_plugin.query_builder.has_channel"
           - "@bitbag_sylius_elasticsearch_plugin.query_builder.contains_name"
           - "@bitbag_sylius_elasticsearch_plugin.query_builder.has_product_taxon"
           - "@bitbag_sylius_elasticsearch_plugin.query_builder.has_options"
           - "@bitbag_sylius_elasticsearch_plugin.query_builder.has_attributes"
           - "@bitbag_sylius_elasticsearch_plugin.query_builder.has_price_between"
           - "@app.bitbag.syliuselasticsearchplugin.query_builder.has_fieldname"
           - "%bitbag_es_shop_option_property_prefix%"
           - "%bitbag_es_shop_attribute_property_prefix%"

```
