### ISSUE TITLE
Index field amount error: A lot of product attributes

### ISSUE THREAD

**Issue by psihius** [BitBagCommerce/SyliusElasticsearchPlugin#41]
We have a database that is automotive parts db, meaning there are over a thousand product attributes of all kinds.

When used with default Elastic settings, we start to get errors during the import process
```index: /bitbag_shop_products_dev/default/67367 caused Limit of total fields [1000] in index [bitbag_shop_products_dev] has been exceeded```

Current implementation stores attribute as array per attribute on the document itself, as `attribute_%attribute_name% => [ %values% ]`. This results in an index structure ballooning to over 1000 fields.

**Comment by bitbager** [comment]
Fixed :)

**Comment by euperia** [comment]
For future reference, this is how you can set the total field limit:

```
# config/packages/fos_elastica.yml

fos_elastica:
    clients:
            default: { host: 127.0.0.1, port: 9200 }
    indexes:
        bitbag_shop_product:
            settings:
                index.mapping.total_fields.limit: 10000
```
