### ISSUE TITLE
Redirection does not work

### ISSUE THREAD

**Issue by maximehuran** [BitBagCommerce/SyliusElasticsearchPlugin#60]
Hi,

I am trying to create the redirection 

I followed the documentation in putting on the `` file : 
```yaml
redirect_sylius_shop_product_index:
    path: /{_locale}/taxons/{slug}
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: bitbag_sylius_elasticsearch_plugin_shop_list_products
        permanent: true
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
        slug: .+
```

It does not work and I still see the original product list page.
Since, I removed the locale in the URL so changed the redirection like this : 
```yaml
redirect_sylius_shop_product_index:
    path: /taxons/{slug}
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: bitbag_sylius_elasticsearch_plugin_shop_list_products
        permanent: true
    requirements:
        slug: .+
```

But it still the same issue and always see the original product list page.
Do you know why ? 
I am on Sylius 1.4.4

FYI, I used this now for the routing without locale : 
```yaml
bitbag_sylius_elasticsearch_plugin_shop_list_products:
    path: /products-list/{slug}
    defaults:
        _controller: bitbag_sylius_elasticsearch_plugin.controller.action.shop.list_products
        template: "@BitBagSyliusElasticsearchPlugin/Shop/Product/index.html.twig"
    requirements:
        slug: .+

bitbag_sylius_elasticsearch_plugin_shop_auto_complete_product_name:
    path: /auto-complete/product
    defaults:
        _controller: bitbag_sylius_elasticsearch_plugin.controller.action.shop.auto_complete_product_name
    requirements:
        slug: .+
```

**Comment by bitbager** [comment]
Add this snippet to your `sylius_shop_routing.yaml`.

```
redirect_sylius_shop_product_index:
    path: /{_locale}/taxons/{slug}
    controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::redirectAction
    defaults:
        route: bitbag_sylius_elasticsearch_plugin_shop_list_products
        permanent: true
    requirements:
        _locale: ^[a-z]{2}(?:_[A-Z]{2})?$
        slug: .+
```

Also, remember about updating tempaltes with the new routing.
